#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

UBUNTU_DISTRO="${UBUNTU_DISTRO:-ubuntu}"
GATEWAY_PORT="${GATEWAY_PORT:-18789}"
GATEWAY_BIND="${GATEWAY_BIND:-loopback}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PLUGIN_DIR="${REPO_ROOT}/openclaw-plugin-mobile-ui"
RUNNER_SCRIPT="${REPO_ROOT}/installer/ubuntu/mobile-runner.sh"

# ---- choose droidrun provider/model in Termux, then pass to Ubuntu via env file ----
TMP_ENV="${TMPDIR:-/data/data/com.termux/files/usr/tmp}/clawbot-env.$$.sh"
trap 'rm -f "$TMP_ENV"' EXIT

DROIDRUN_PROVIDER_CHOSEN="${DROIDRUN_PROVIDER:-}"
DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL:-}"

pick_llm_termux() {
  if [ -n "${DROIDRUN_PROVIDER_CHOSEN}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN}" ]; then
    return 0
  fi

  if [ -n "${GEMINI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Gemini"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gemini-2.5-flash}"
    return 0
  fi

  if [ -n "${OPENAI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="OpenAI"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gpt-5.2}"
    return 0
  fi

  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Anthropic"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-claude-opus-4-6}"
    return 0
  fi

  if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="DeepSeek"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-deepseek-reasoner}"
    return 0
  fi

  return 1
}

if pick_llm_termux; then
  echo "[run] picked droidrun llm in termux: provider=${DROIDRUN_PROVIDER_CHOSEN} model=${DROIDRUN_MODEL_CHOSEN}"
else
  echo "[run] WARNING: no LLM key found in Termux env. Set one of GEMINI_API_KEY/OPENAI_API_KEY/ANTHROPIC_API_KEY/DEEPSEEK_API_KEY."
fi

{
  echo "# generated by run.sh"

  if [ -n "${DROIDRUN_PROVIDER_CHOSEN:-}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN:-}" ]; then
    printf "export DROIDRUN_PROVIDER=%q\n" "${DROIDRUN_PROVIDER_CHOSEN}"
    printf "export DROIDRUN_MODEL=%q\n" "${DROIDRUN_MODEL_CHOSEN}"
  fi

  case "${DROIDRUN_PROVIDER_CHOSEN:-}" in
    Gemini)    [ -n "${GEMINI_API_KEY:-}" ] && printf "export GEMINI_API_KEY=%q\n" "$GEMINI_API_KEY" ;;
    OpenAI)    [ -n "${OPENAI_API_KEY:-}" ] && printf "export OPENAI_API_KEY=%q\n" "$OPENAI_API_KEY" ;;
    Anthropic) [ -n "${ANTHROPIC_API_KEY:-}" ] && printf "export ANTHROPIC_API_KEY=%q\n" "$ANTHROPIC_API_KEY" ;;
    DeepSeek)  [ -n "${DEEPSEEK_API_KEY:-}" ] && printf "export DEEPSEEK_API_KEY=%q\n" "$DEEPSEEK_API_KEY" ;;
  esac
} > "$TMP_ENV"

if [ ! -x "$RUNNER_SCRIPT" ]; then
  echo "[run] ERROR: runner script not found at $RUNNER_SCRIPT" >&2
  exit 1
fi

echo "[clawbot] Starting OpenClaw Gateway..."
proot-distro login "${UBUNTU_DISTRO}" --shared-tmp -- bash -lc 'bash -seuo pipefail' <<EOF
export TMP_ENV='${TMP_ENV}'
export GATEWAY_PORT='${GATEWAY_PORT}'
export GATEWAY_BIND='${GATEWAY_BIND}'
exec '${RUNNER_SCRIPT}' start-gateway
EOF
